version: "3"
services:
  haystack-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - {{ deployments[client].haystack_port }}:8000
    volumes:
      # Optional: mount your own models from disk into the container
      - "./models:/home/user/models"
      - "./data:/home/user/data"
    environment:
      - DB_HOST=elasticsearch
      - QUERY_PIPELINE_NAME=query2
      - ROOT_PATH=/{{ client }}
    restart: always
    depends_on:
      - elasticsearch
    command: "/bin/bash -c 'sleep 15 && gunicorn rest_api.application:app -b 0.0.0.0 -k uvicorn.workers.UvicornWorker --workers 1 --timeout 180 --preload'"
  elasticsearch:
    image: "elasticsearch:7.9.2"
    volumes:
      - "{{ client_elasticsearch_data_folder }}:/usr/share/elasticsearch/data"
    environment:
      - discovery.type=single-node
