all:
  children:
    sandbox:
      hosts:
        datascience-01.infra.data.gouv.fr:
          ansible_python_interpreter: /usr/bin/python3
          deployments:
            cnil:
              haystack_port: 8080
            crpa:
              haystack_port: 8003
            dila:
              haystack_port: 8004