all:
  children:
    sandbox:
      hosts:
        datascience-01.infra.data.gouv.fr:
          ansible_python_interpreter: /usr/bin/python3
          installation_directory: /data/piaf-ml
          # this can be retrieved from https://github.com/deepset-ai/haystack
          haystack_commit: 0168f04
          haystack_python_dependencies:
            - mmh3
            - sentence-transformers
            - pytest
          deployments:
            cnil:
              haystack_port: 8002
            crpa:
              haystack_port: 8003
            dila:
              haystack_port: 8004