version: "3"
services:
  haystack-api:
    build:
      context: .
      dockerfile: Dockerfile
    # image: "deepset/haystack-cpu:latest"
    ports:
      - 8004:8000
    environment:
      # See rest_api/pipelines.yaml for configurations of Search & Indexing Pipeline.
      - ELASTICSEARCHDOCUMENTSTORE_PARAMS_HOST=elasticsearch
      - DB_HOST=elasticsearch
      - USE_GPU=False
      - TOP_K_PER_SAMPLE=3 # how many answers can come from the same small passage (reduce value for more variety of answers)
      - QUERY_PIPELINE_NAME=query2
      - ROOT_PATH=/dila
    volumes:
      # Optional: mount your own models from disk into the container
      - "./models:/home/user/models"
      - "./data:/home/user/data"
    restart: always
    depends_on:
      - elasticsearch
    command: "/bin/bash -c 'sleep 15 && gunicorn rest_api.application:app -b 0.0.0.0 -k uvicorn.workers.UvicornWorker --workers 1 --timeout 180'"
  elasticsearch:
    image: "elasticsearch:7.9.2"
    environment:
      - discovery.type=single-node
