version: "3.3"
services:
  non-regression-tests:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MLFLOW_SSH_USERNAME=${MLFLOW_SSH_USERNAME}
        - MLFLOW_SSH_HOSTNAME=${MLFLOW_SSH_HOSTNAME}
    depends_on:
      - elasticsearch
    secrets:
      - source: ssh-private-key
        target: .ssh/id_rsa
    volumes:
      - $HOME/.cache/huggingface:/root/.cache/huggingface
      - ${TEST_DATASET}:/usr/local/share/non-regression-tests/fquad_eval.json
    env_file: .env
    restart: always
  elasticsearch:
    image: "elasticsearch:7.13.2"
    environment:
      - discovery.type=single-node
    restart: always

secrets:
  ssh-private-key:
    file: ${MLFLOW_SSH_PRIVATE_KEY}
