name: Tests


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Run ES
      run: docker run -d -p 9200:9200 -e "discovery.type=single-node" -e "ES_JAVA_OPTS=-Xms128m -Xmx128m" elasticsearch:7.9.2
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install --exists-action=w -r requirements_simplified.txt 
    
    - name: Test with pytest
      run: |
        pytest test
